### ISSUE TITLE
How to prepare the training dataset " words_alpha_train_unique.txt"

### ISSUE THREAD

**Issue by tsbiosky** [ryanyuan42/transformer-hangman-bot#1]
I try to mask the "words_alpha_train.txt" or my own dataset to build a txt file similar to  " words_alpha_train_unique.txt". But they both get Loss: NaN in training . Would you like to tell me how to prepare the  " words_alpha_train_unique.txt" thanks.

Here is my code :
![1688506058074](https://github.com/ryanyuan42/transformer-hangman-bot/assets/31939883/91c3de2b-a157-4b19-be7b-c4247b5bad71)

**Comment by ryanyuan42** [comment]
@tsbiosky Hi, I guess if you want to mask a word, you probably need to mask all the same letters. For example, in hello, if you choose to mask the letter l, it should become he##o.
